# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

name: $(buildversion)
steps:
- script: echo devops pat $(devops-pat-versionnumber)
  displayName: 'Run a one-line script'

- task: versioncounter@1
  inputs:
    VersionVariable: 'buildversion'
    UpdateMinorVersion: true
    MaxValuePatchVersion: '100'
    DevOpsPat: '$(devops-pat-versionnumber)'

